services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Chanathale\ChanathaleCommand\:
    resource: '../Classes/*'
    exclude: '../Classes/{Domain/Model,Utility}'

  Chanathale\ChanathaleCommand\Command\RedirectImportCommand:
    tags:
      - name: 'console.command'
        command: 'chanathale:importRedirects'